delta admin.std.json admin.json
delta balance.std.json balance.json
delta bw.std.json bw.json
delta charge.std.json charge.json
delta customer.std.json customer.json
delta extra_charge.std.json extra_charge.json
delta group.std.json group.json
delta import_file.std.json import_file.json
delta invoice.std.json invoice.json
delta ippool.std.json ippool.json
delta isp.std.json isp.json
delta ldap.std.json ldap.json
delta log_console.std.json log_console.json
delta login.std.json login.json
delta mc.std.json mc.json
delta notification.std.json notification.json
delta online_payment.std.json online_payment.json
delta perm.std.json perm.json
delta ras.std.json ras.json
delta report.std.json report.json
delta session.std.json session.json
delta snapshot.std.json snapshot.json
delta stat.std.json stat.json
delta SystemNotification.std.json SystemNotification.json
delta telephony_support.std.json telephony_support.json
delta user_balance.std.json user_balance.json
delta user_custom_field.std.json user_custom_field.json
delta user.std.json user.json
delta util.std.json util.json
delta voip_provider.std.json voip_provider.json
delta voucher.std.json voucher.json
