#!/bin/bash
set -e

if ! which xmllint ; then
	echo "intsall xmllint with: sudo apt install libxml2-utils"
	exit 1
fi

for FILE in "$@" ; do
	xmllint --format "$FILE" > "$FILE.tmp"
	mv "$FILE.tmp" "$FILE"
done

